DROP TABLE IF EXISTS `tb_user`;
CREATE TABLE `tb_user` (
		`ID` VARCHAR(36) NOT NULL DEFAULT '',
		`U_State` TINYINT NOT NULL DEFAULT '1' COMMENT '1: OK, 0: Bad',
		`U_Type` INTEGER NOT NULL DEFAULT '7' COMMENT '0x1: lic create,0x10 lic manage,0x100 log',
		`U_LastLogin` BIGINT NOT NULL DEFAULT '0',
		`U_LastSync` BIGINT NOT NULL DEFAULT '0',
		`U_CreateTime` BIGINT NOT NULL DEFAULT '0',
		`U_Name` VARCHAR(128) NOT NULL DEFAULT '',
		`U_Password` VARCHAR(256) NOT NULL DEFAULT '',
		`U_UKey` VARCHAR(36) NOT NULL DEFAULT '' COMMENT 'UKEY Id',
		`U_Email` VARCHAR(256) NOT NULL DEFAULT '',
		`U_PhoneNumber` VARCHAR(32) NOT NULL DEFAULT '',
		`U_Desc` VARCHAR(1024) NOT NULL DEFAULT '',
		PRIMARY KEY (`ID`)
) ENGINE=Innodb DEFAULT CHARSET=utf8;
ALTER TABLE tb_user ADD INDEX tb_user_id (ID);
ALTER TABLE tb_user ADD INDEX tb_user_type (U_Type);
ALTER TABLE tb_user ADD INDEX tb_user_name (U_Name);

DROP TABLE IF EXISTS `tb_misc`;
CREATE TABLE `tb_misc` (
		`ID` BIGINT NOT NULL AUTO_INCREMENT,
		`M_Name` VARCHAR(64) NOT NULL DEFAULT '',
		`M_Value` VARCHAR(64) NOT NULL DEFAULT '',
		`M_Type` VARCHAR(64) NOT NULL DEFAULT '',
		PRIMARY KEY (`ID`)
) ENGINE=Innodb DEFAULT CHARSET=utf8;
ALTER TABLE tb_misc ADD INDEX tb_misc_id (ID);
ALTER TABLE tb_misc ADD INDEX tb_misc_name (M_Name);
