// Auto generated by System, don't modify this file
package api

func InitApiService() {

	var service *ApiService

	GApiServices = make(map[string]*ApiService, 10000)

	// --------------------
	// for APIAddAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIAddAccount"
	service.Handler = APIAddAccount
	GApiServices["octlink.mirage.center.user.APIAddAccount"] = service

	// --------------------
	// for APIDeleteAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIDeleteAccount"
	service.Handler = APIDeleteAccount
	GApiServices["octlink.mirage.center.user.APIDeleteAccount"] = service

	// --------------------
	// for APILogOut
	// --------------------
	service = new(ApiService)
	service.Name = "APILogOut"
	service.Handler = APILogOut
	GApiServices["octlink.mirage.center.user.APILogOut"] = service

	// --------------------
	// for APILoginByAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APILoginByAccount"
	service.Handler = APILoginByAccount
	GApiServices["octlink.mirage.center.user.APILoginByAccount"] = service

	// --------------------
	// for APIResetAccountPassword
	// --------------------
	service = new(ApiService)
	service.Name = "APIResetAccountPassword"
	service.Handler = APIResetAccountPassword
	GApiServices["octlink.mirage.center.user.APIResetAccountPassword"] = service

	// --------------------
	// for APIShowAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAccount"
	service.Handler = APIShowAccount
	GApiServices["octlink.mirage.center.user.APIShowAccount"] = service

	// --------------------
	// for APIShowAccountList
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAccountList"
	service.Handler = APIShowAccountList
	GApiServices["octlink.mirage.center.user.APIShowAccountList"] = service

	// --------------------
	// for APIShowAllAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIShowAllAccount"
	service.Handler = APIShowAllAccount
	GApiServices["octlink.mirage.center.user.APIShowAllAccount"] = service

	// --------------------
	// for APIUpdateAccount
	// --------------------
	service = new(ApiService)
	service.Name = "APIUpdateAccount"
	service.Handler = APIUpdateAccount
	GApiServices["octlink.mirage.center.user.APIUpdateAccount"] = service

	// --------------------
	// for APIUpdateAccountPassword
	// --------------------
	service = new(ApiService)
	service.Name = "APIUpdateAccountPassword"
	service.Handler = APIUpdateAccountPassword
	GApiServices["octlink.mirage.center.user.APIUpdateAccountPassword"] = service

	// --------------------
	// for APIAddHost
	// --------------------
	service = new(ApiService)
	service.Name = "APIAddHost"
	service.Handler = APIAddHost
	GApiServices["octlink.mirage.center.host.APIAddHost"] = service

	// --------------------
	// for APIDeleteHost
	// --------------------
	service = new(ApiService)
	service.Name = "APIDeleteHost"
	service.Handler = APIDeleteHost
	GApiServices["octlink.mirage.center.host.APIDeleteHost"] = service
}
